# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

{
	"name": "com-lint",
	"version": "0.0.0-development",
	"description": "A GitHub App that runs commitlint for you",
	"author": "Ammar Ahmed Butt <ammar.butt@atlassiancommunity.com> (https://ammarahmed.cf)",
	"license": "MIT",
	"repository": "https://github.com/Ammar-Knowledge/com-lint.git",
	"keywords": [
		"validate",
		"commit",
		"pr",
		"conventional",
		"git",
		"probot-app"
	],
	"main": "index.js",
	"scripts": {
		"now-start": "PRIVATE_KEY=$(echo $PRIVATE_KEY | base64 -d) npm start",
		"start": "probot run ./index.js",
		"test": "jest"
	},
	"files": [
		"lib",
		"index.js",
		"README.md"
	],
	"dependencies": {
		"@commitlint/core": "^17.6.3",
		"@commitlint/parse": "^17.4.4",
		"@commitlint/types": "^17.4.4",
		"@commitlint/utils": "^6.0.2",
		"@octokit/webhooks": "^11.0.0",
		"commitlint": "^17.6.3",
		"conventional-changelog-conventionalcommits": "^5.0.0",
		"express": "^4.18.2",
		"jsonc-parser": "^3.2.0",
		"minimist": "^1.2.8",
		"octokit": "^2.0.14",
		"probot": "^12.3.0"
	},
	"devDependencies": {
		"@commitlint/cli": "^17.6.3",
		"@commitlint/config-angular": "^17.6.3",
		"@commitlint/config-conventional": "^17.6.3",
		"eslint": "^8.40.0",
		"eslint-plugin-json": "^3.1.0",
		"jest": "^29.5.0",
		"smee-client": "^1.2.3"
	},
	"engines": {
		"node": "18.x",
		"npm": "9.6.x"
	},
	"jest": {
		"testEnvironment": "node"
	}
}